FoodSafari/trydjango2/fooditem/urls.py
from django.urls import path


from fooditem.views import (
    FoodItemCreateView,
    FoodItemListView,
    FoodItemDetailView,
    FoodItemUpdateView,

)



app_name = "fooditem"

urlpatterns = [
    path('', FoodItemListView.as_view(), name="list"),


    path('<str:pk>/', FoodItemDetailView.as_view(), name="detail"),
    #path('<str:pk>/update/', FoodItemUpdateView.as_view(), name="update"),
    # path('create/', FoodItemCreateView.as_view(), name="create"),


]

FoodSafari/trydjango2/orderitem/urls.py
from django.urls import path
from orderitem.views import FoodOrderedCreateView


app_name = "orderitem"

urlpatterns = [
    path('create/', FoodOrderedCreateView.as_view(), name="order"),


]

FoodSafari/trydjango2/trydjango2/urls.py
# """trydjango2 URL Configuration
#
# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/2.2/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """
# # from django.contrib import admin
# # from django.urls import path
# # #from resturants.views import home_view,hotel,contact
# # from resturants.views import ContactView    #home URL
# #
# #
# # urlpatterns = [                            #endpoints
# #     path('admin/', admin.site.urls),
# #     path("home/",home_view),             #to open home path.....first parameter as the endpoint and the second parameter as the function
# #     path("hotel/",hotel),
# #     path("contact/",ContactView.as_view()),#as_view() make the class callable but generally class is not callabe
# # ]
#
# from django.contrib import admin
# from django.urls import path
# from resturants.views import ContactView
# from resturants.views import (
#     resturant_list,
#     ResturantListView,
#     ResturantDetailView,
#     ResturantCreateView
# )
# from django.views.generic import TemplateView
# from userauth.views import SignUpView, UserProfileView, UserLoginView, UserProfileUpdateView
# from django.contrib.auth.views import LogoutView
#
#
# #from userauth.views import SignUpView,CustomLoginView
#
#
# urlpatterns = [
#                                                     #path('endpoints/, function/class())
#     path('admin/', admin.site.urls),
#     path('login/', UserLoginView.as_view()),
#     path('signup/', SignUpView.as_view()),
#     path('logout/', LogoutView.as_view(next_page="/login/")),       #it is used to make logout
#     path('user-profile/', UserProfileView.as_view()),
#     path('user-profile/update/', UserProfileUpdateView.as_view()),
#
#     #path('users/login', CustomLoginView.as_view()),
#     #path('users/signup', SignUpView.as_view()),
#
#     path("contact/",ContactView.as_view()),
#
#     #path('resturants/',resturant_list),
#     path('resturants/', ResturantListView.as_view()),
#
#     path('resturants/create/', ResturantCreateView.as_view()),
#
#     #path('resturants/create/', resturant_createview),
#
#     #path('resturants/<str:slug>/', ResturantListView.as_view()),
#     path('resturants/<str:slug>/', ResturantDetailView.as_view()),
#
#     #path('resturants/<int:rest_id>/',ResturantDetailView.as_view()),
#
#     path('home/', TemplateView.as_view(template_name="home.html")),
#     path('hotel/', TemplateView.as_view(template_name="hotel.html")),
#
#     #path('resturants/veg', VegResturantListView.as_view()),
#     #path('resturants/nonveg', NonVegResturantListView.as_view()),
#
#     #<data_type :var_name>  #to declare varibale inside endpoints
#
# ]

from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

from resturants.views import  HomeTemplateView
#from  mail.views import sendmail

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("userauth.urls", namespace="userauth")),        #namespace is  used when we need to insert the all userauth related url in trydjango2
    path('resturants/', include("resturants.urls", namespace="resturants")),
    path('items/', include("fooditem.urls", namespace="fooditem")),
    path('order/', include("orderitem.urls", namespace="orderitem")),


    path('home/', HomeTemplateView.as_view(),name="home"),

    path('', include('sendemail.urls')),
#path('notify/',sendmail),       #used to send email
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

FoodSafari/trydjango2/userauth/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from userauth.views import SignUpView, UserProfileView, UserLoginView, UserProfileUpdateView
app_name= "userauth"
urlpatterns = [
    path('login/', UserLoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(next_page="/login/"), name="logout"),
    path('signup/', SignUpView.as_view(), name="signup"),
    path('user-profile/', UserProfileView.as_view(), name="profile"),
    path('user-profile/update/', UserProfileUpdateView.as_view(), name="update"),

]

FoodSafari/trydjango2/templates/snippets/css.html
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

FoodSafari/trydjango2/templates/snippets/js.html
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

FoodSafari/trydjango2/templates/snippets/nav.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}"><font size="2"><font color="#ffffff">HOME</font></font></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'fooditem:list' %}"><font size="2"><font color="#ffffff">MENUS</font></font></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'resturants:list' %}"><font size="2"><font color="#ffffff">RESTURANT</font></font></a>
            </li>

             <li class="nav-item">
                <a class="nav-link" href="{% url 'orderitem:order' %}"><font size="2"><font color="#ffffff">ORDER</font></font></a>
            </li>

        </ul>
    </div>
    <div class="mx-auto order-0">
        <a class="navbar-brand mx-auto" href="#"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userauth:logout' %}"><font size="2"><font color="#ffffff">LOGOUT</font></font></a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userauth:signup' %}"><font size="2"><font color="#ffffff">SIGNUP</font></font></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userauth:login' %}"><font size="2"><font color="#ffffff">LOGIN</font></font></a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
</nav>