FoodSafari/trydjango2/fooditem/urls.py
from django.urls import path


from fooditem.views import (
    FoodItemCreateView,
    FoodItemListView,
    FoodItemDetailView,
    FoodItemUpdateView,

)



app_name = "fooditem"

urlpatterns = [
    path('', FoodItemListView.as_view(), name="list"),


    path('<str:pk>/', FoodItemDetailView.as_view(), name="detail"),
    #path('<str:pk>/update/', FoodItemUpdateView.as_view(), name="update"),
    # path('create/', FoodItemCreateView.as_view(), name="create"),


]

FoodSafari/trydjango2/trydjango2/urls.py
# """trydjango2 URL Configuration
#
# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/2.2/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """
# # from django.contrib import admin
# # from django.urls import path
# # #from resturants.views import home_view,hotel,contact
# # from resturants.views import ContactView    #home URL
# #
# #
# # urlpatterns = [                            #endpoints
# #     path('admin/', admin.site.urls),
# #     path("home/",home_view),             #to open home path.....first parameter as the endpoint and the second parameter as the function
# #     path("hotel/",hotel),
# #     path("contact/",ContactView.as_view()),#as_view() make the class callable but generally class is not callabe
# # ]
#
# from django.contrib import admin
# from django.urls import path
# from resturants.views import ContactView
# from resturants.views import (
#     resturant_list,
#     ResturantListView,
#     ResturantDetailView,
#     ResturantCreateView
# )
# from django.views.generic import TemplateView
# from userauth.views import SignUpView, UserProfileView, UserLoginView, UserProfileUpdateView
# from django.contrib.auth.views import LogoutView
#
#
# #from userauth.views import SignUpView,CustomLoginView
#
#
# urlpatterns = [
#                                                     #path('endpoints/, function/class())
#     path('admin/', admin.site.urls),
#     path('login/', UserLoginView.as_view()),
#     path('signup/', SignUpView.as_view()),
#     path('logout/', LogoutView.as_view(next_page="/login/")),       #it is used to make logout
#     path('user-profile/', UserProfileView.as_view()),
#     path('user-profile/update/', UserProfileUpdateView.as_view()),
#
#     #path('users/login', CustomLoginView.as_view()),
#     #path('users/signup', SignUpView.as_view()),
#
#     path("contact/",ContactView.as_view()),
#
#     #path('resturants/',resturant_list),
#     path('resturants/', ResturantListView.as_view()),
#
#     path('resturants/create/', ResturantCreateView.as_view()),
#
#     #path('resturants/create/', resturant_createview),
#
#     #path('resturants/<str:slug>/', ResturantListView.as_view()),
#     path('resturants/<str:slug>/', ResturantDetailView.as_view()),
#
#     #path('resturants/<int:rest_id>/',ResturantDetailView.as_view()),
#
#     path('home/', TemplateView.as_view(template_name="home.html")),
#     path('hotel/', TemplateView.as_view(template_name="hotel.html")),
#
#     #path('resturants/veg', VegResturantListView.as_view()),
#     #path('resturants/nonveg', NonVegResturantListView.as_view()),
#
#     #<data_type :var_name>  #to declare varibale inside endpoints
#
# ]

from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

from resturants.views import  HomeTemplateView
#from  mail.views import sendmail

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("userauth.urls", namespace="userauth")),        #namespace is  used when we need to insert the all userauth related url in trydjango2
    path('resturants/', include("resturants.urls", namespace="resturants")),
    path('items/', include("fooditem.urls", namespace="fooditem")),
    path('order/', include("orderitem.urls", namespace="orderitem")),


    path('home/', HomeTemplateView.as_view(),name="home"),

    path('', include('sendemail.urls')),
#path('notify/',sendmail),       #used to send email
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

FoodSafari/trydjango2/fooditem/models.py
from django.db import models
from userauth.models import CustomUser
from resturants.models import ResturantLocation

a = list()

# Create your models here.
class FoodItem(models.Model):
    # associations
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    resturant = models.ForeignKey(ResturantLocation, on_delete=models.CASCADE)

    # FoodItems data
    name = models.CharField(max_length=100)                         #food item name
    category = models.CharField(max_length=100,null=True,blank=True)
    price=models.CharField(max_length=120,null=True,blank=True)
    contents = models.TextField(help_text='seperate by comma')
    excludes = models.TextField(help_text='seperate by comma', blank=True, null=True)   #
    public = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    image=models.ImageField(upload_to="profile_image",blank=True,null=True)

    def __str__(self):
        return self.user

    class Meta:     #Meta is like class description
        ordering = ["-updated", "-timestamp"]

    def __str__(self):
        return self.name

    def __repr__(self):
        return f"{__class__.__name__}({self.name} <{self.user!r}> <{self.resturant!r}>)"

    def get_contents(self):
        return self.contents.split(",")     #split changes to list

    def get_excludes(self):
        return self.excludes.split(",")

FoodSafari/trydjango2/fooditem/forms.py
from django import forms

from .models import FoodItem
from resturants.models import ResturantLocation


class FoodItemForm(forms.ModelForm):
    class Meta:
        model = FoodItem
        fields = (
            "resturant",
            "name",
            "price",
            "category",
            "contents",
            "excludes",
            "public",
            "image"
        )

    def __init__(self, user, *args, **kwargs):      #it is used show that we can show only particular user resturant
        super().__init__(*args, **kwargs)
        self.user = user
        print(kwargs)
        self.fields["resturant"].queryset = ResturantLocation.objects.filter(owner=self.user)   #it is used so that  it only shows the resturant list which we made and  shoulnot display those resturant which are made by others
        #here field is resturant,name,content,exclude,public
        #here we are also filterin the queryset

FoodSafari/trydjango2/fooditem/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from .models import FoodItem
from .forms import FoodItemForm
from django.contrib.auth.mixins import LoginRequiredMixin




# Create your views here.
class FoodItemListView(LoginRequiredMixin,ListView):
    login_url = reverse_lazy("userauth:login")
    template_name = "fooditem/list.html"
    def get_queryset(self):
        return FoodItem.objects.filter(user__username__exact=self.request.user)


class FoodItemDetailView(LoginRequiredMixin,DetailView):
    login_url = reverse_lazy("userauth:login")
    template_name = "fooditem/detail.html"
    def get_queryset(self):
        return FoodItem.objects.filter(user__username__exact=self.request.user)

class FoodItemCreateView(LoginRequiredMixin,CreateView):
    login_url = reverse_lazy("userauth:login")
    form_class = FoodItemForm
    template_name = "fooditem/form.html"
    success_url = reverse_lazy("fooditem:list")

    def get_form_kwargs(self):              #sending user info to form.py using form view function or class
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user =self.request.user
        return super().form_valid(form)

class FoodItemUpdateView(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy("userauth:login")
    template_name = "fooditem/form.html"
    form_class = FoodItemForm
    success_url = reverse_lazy("fooditem:list")     #reverse_lazy is used when we need only and it shows the error letter but when we used reverse then it shows the errors earlier

    def get_queryset(self):
        return FoodItem.objects.filter(user=self.request.user)

    # only for demo  not necessary to define
    def get_object(self, queryset=None):
        item_id = self.kwargs.get("pk")                #primary key
        item_detail = get_object_or_404(FoodItem, pk=item_id)
        return item_detail

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

FoodSafari/trydjango2/fooditem/templates/fooditem/detail.html
{% extends "base.html" %}
{% block content %}
    {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'fooditem/food_list.css' %}">
 <br><br><br><br><h1><font color="#ffffff"><center><h1><b><font size="7">Menus's</font></b></h1></center></font></h1><br>
               <br><br><h1>{{ object.name }} <small>{{ object.resturant }}</small></h1>
                <i><b><font size="4"><br><h3>Contents</h3>
                {% if object.contents %}
                    {% for item in object.get_contents %}
                        <li>{{ item }}</li>
                    {% endfor %}
                {% endif %}<br>
                    <h3>Excludes</h3>
                {% if object.excludes %}
                    {% for item in object.get_excludes %}
                        <li>{{ item }}</li>
                    {% endfor %}
                {% endif %}<br>
                <img src="{{ fooditem.image.url }}" width="240"><br><br>
                <p><i>Added to database on:</i> {{ object.timestamp|date }} || <i>Updated:</i> {{ object.updated|timesince }} ago</p>
                </font></b></i>

<br><br><br>
{% endblock %}

FoodSafari/trydjango2/fooditem/templates/fooditem/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Add FoodItem</h1>
    <form method='POST'>

        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Save</button>

    </form>
{% endblock %}

FoodSafari/trydjango2/fooditem/templates/fooditem/list.html
{% extends "base.html" %}
{% block content %}
    {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'fooditem/food_list.css' %}">
<hr>

<div class="container">
  <div class="row-fluid">
    <div class="span10 offsetHalf">

		<i class="icon-screenshot icon-5x" style="color:#ee1111;"></i>
    </div>
  </div>

  <div class="row-fluid">

      	<div class="span5 offsetHalf block">
          <div class="pull-center"><br>
              <h1><font color="#ffffff"><center><h1><b><font size="7">Veg Menu's</font></b></h1></center></font></h1>
                <b>{% for item in object_list %}
              {% if item.category == 'veg' %}
                    <li style="list-style-type:none;"><a href="{% url 'fooditem:detail' pk=item.id %}"><font color="#ffffff"><font size="4"><center>{{ item.name }}    --------------------------------------------------------------- Rs. {{item.price}}</center></font></font></a></li>
              {%endif%}
              {% endfor %}
                </b>
      	</div>
        <br><br><br><br><br><br>
      <div class="span5 offsetHalf block">
          <div class="pull-center"><br>
              <h1><font color="#ffffff"><center><h1><b><font size="7">Non-Veg Menu's</font></b></h1></center></font></h1>
                <b>{% for item in object_list %}
              {% if item.category == 'non-veg' %}
                    <li style="list-style-type:none;"><a href="{% url 'fooditem:detail' pk=item.id %}"><font color="#ffffff"><font size="4"><center>{{ item.name }}    --------------------------------------------------------------- Rs. {{item.price}}</center></font></font></a></li>
              {%endif%}
              {% endfor %}
                </b></div>
      	</div>


</div><!---/cont---->

</div>
    <br><br><br><br><br>


{% endblock %}