FoodSafari/trydjango2/fooditem/urls.py
from django.urls import path


from fooditem.views import (
    FoodItemCreateView,
    FoodItemListView,
    FoodItemDetailView,
    FoodItemUpdateView,

)



app_name = "fooditem"

urlpatterns = [
    path('', FoodItemListView.as_view(), name="list"),


    path('<str:pk>/', FoodItemDetailView.as_view(), name="detail"),
    #path('<str:pk>/update/', FoodItemUpdateView.as_view(), name="update"),
    # path('create/', FoodItemCreateView.as_view(), name="create"),


]

FoodSafari/trydjango2/resturants/urls.py
from django.urls import path
from resturants.views import (
    ResturantListView,
    ResturantDetailView,
    ResturantCreateView,
)
app_name= "resturants"
urlpatterns = [
    path('', ResturantListView.as_view(), name="list"),
    path('create/', ResturantCreateView.as_view(), name="create"),
    path('<str:slug>/', ResturantDetailView.as_view(), name="detail"),

]

FoodSafari/trydjango2/trydjango2/urls.py
# """trydjango2 URL Configuration
#
# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/2.2/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """
# # from django.contrib import admin
# # from django.urls import path
# # #from resturants.views import home_view,hotel,contact
# # from resturants.views import ContactView    #home URL
# #
# #
# # urlpatterns = [                            #endpoints
# #     path('admin/', admin.site.urls),
# #     path("home/",home_view),             #to open home path.....first parameter as the endpoint and the second parameter as the function
# #     path("hotel/",hotel),
# #     path("contact/",ContactView.as_view()),#as_view() make the class callable but generally class is not callabe
# # ]
#
# from django.contrib import admin
# from django.urls import path
# from resturants.views import ContactView
# from resturants.views import (
#     resturant_list,
#     ResturantListView,
#     ResturantDetailView,
#     ResturantCreateView
# )
# from django.views.generic import TemplateView
# from userauth.views import SignUpView, UserProfileView, UserLoginView, UserProfileUpdateView
# from django.contrib.auth.views import LogoutView
#
#
# #from userauth.views import SignUpView,CustomLoginView
#
#
# urlpatterns = [
#                                                     #path('endpoints/, function/class())
#     path('admin/', admin.site.urls),
#     path('login/', UserLoginView.as_view()),
#     path('signup/', SignUpView.as_view()),
#     path('logout/', LogoutView.as_view(next_page="/login/")),       #it is used to make logout
#     path('user-profile/', UserProfileView.as_view()),
#     path('user-profile/update/', UserProfileUpdateView.as_view()),
#
#     #path('users/login', CustomLoginView.as_view()),
#     #path('users/signup', SignUpView.as_view()),
#
#     path("contact/",ContactView.as_view()),
#
#     #path('resturants/',resturant_list),
#     path('resturants/', ResturantListView.as_view()),
#
#     path('resturants/create/', ResturantCreateView.as_view()),
#
#     #path('resturants/create/', resturant_createview),
#
#     #path('resturants/<str:slug>/', ResturantListView.as_view()),
#     path('resturants/<str:slug>/', ResturantDetailView.as_view()),
#
#     #path('resturants/<int:rest_id>/',ResturantDetailView.as_view()),
#
#     path('home/', TemplateView.as_view(template_name="home.html")),
#     path('hotel/', TemplateView.as_view(template_name="hotel.html")),
#
#     #path('resturants/veg', VegResturantListView.as_view()),
#     #path('resturants/nonveg', NonVegResturantListView.as_view()),
#
#     #<data_type :var_name>  #to declare varibale inside endpoints
#
# ]

from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

from resturants.views import  HomeTemplateView
#from  mail.views import sendmail

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("userauth.urls", namespace="userauth")),        #namespace is  used when we need to insert the all userauth related url in trydjango2
    path('resturants/', include("resturants.urls", namespace="resturants")),
    path('items/', include("fooditem.urls", namespace="fooditem")),
    path('order/', include("orderitem.urls", namespace="orderitem")),


    path('home/', HomeTemplateView.as_view(),name="home"),

    path('', include('sendemail.urls')),
#path('notify/',sendmail),       #used to send email
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

FoodSafari/trydjango2/resturants/models.py
from django.db import models
from django.db.models.signals import pre_save, post_save
from .utils import unique_slug_generator
from .validators import validate_resturant_category, validate_resturant_name
from userauth.models import CustomUser

# Create your models here.
class ResturantLocation(models.Model):      # we are making the resturant related database in table
    name=models.CharField(max_length=120,validators=[validate_resturant_name])      #it is used to check whether the resturant name is "create" or not, if yes then it is not valid
    location=models.CharField(max_length=120,null=True,blank=True)     #null and blank: if we leave blank then it work as it is True

    category = models.CharField(max_length=120, null=True, blank=True, validators=[validate_resturant_category])
    owner = models.ForeignKey(CustomUser, blank=True, null=True, on_delete=models.CASCADE)      #CASCADE: it used to delete the entire related data of that user in database,when we delete that user


    timestamp=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    menus = models.CharField(max_length=120, null=True, blank=True)
    slug=models.SlugField(null=True,blank=True)     #it is used to make the browser address beautiful

    def __str__(self):
        return self.name


def pre_save_receiver(sender, instance, *args, **kwargs):
    print("saving {}".format(instance))         #instance means object like Bota resturant,name,location,category etc
    if not instance.slug:           #it adds something into the slug it is not wriiten in database
        instance.slug = unique_slug_generator(instance)


def post_save_receiver(sender, instance, created, *args, **kwargs):
    print("saved {}".format(created))

pre_save.connect(pre_save_receiver, sender=ResturantLocation)

post_save.connect(post_save_receiver, sender=ResturantLocation)

FoodSafari/trydjango2/resturants/forms.py
from django import forms
from .models import ResturantLocation


class ResturantLocationModelForm(forms.ModelForm):  #advantage-dynamic,consistency and it will do the same function as ResturantCreateForm
    class Meta:                 #it is going to define the behaviour of the ResturantLocation model form
        model=ResturantLocation
        #fileds="__all__"       # to include all the field
        fields=[                #to include particular field
            "name",
            "location",
            "category",
            "menus",
            "slug"
        ]

FoodSafari/trydjango2/resturants/views.py
from django.shortcuts import render,get_object_or_404,get_list_or_404
from django.views import View
from django.views.generic import (          #use ( ) when we to use many import
    TemplateView,
    ListView,
    DetailView,
    CreateView
)
from .models import ResturantLocation

from django.http import HttpResponseRedirect,Http404
from .forms import ResturantLocationModelForm
from django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

class ContactView(TemplateView):
    template_name="contact.html"

    def get_context_data(self,**kwargs):
        context={
            "resturant_name":"109 degrees",
            "items": ["veg momo","chicken momo"],
        }
        return context


def resturant_list(request):
    template_name = "resturants/resturant_list.html"
    query_set = ResturantLocation.objects.all()     # objects: select * from ResturantLocation in sql query
    context = {"resturants": query_set}
    return render(request, template_name, context)



class ResturantListView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy("userauth:login")
    template_name = "resturants/resturant_list.html"

    def get_queryset(self):
        user = self.request.user
        if user.is_authenticated:
            queryset = ResturantLocation.objects.filter(owner__username__exact=user)
        else:
            raise Http404
        return queryset



class ResturantDetailView(DetailView):
    template_name = "resturants/resturantlocation_detail.html"
    def get_object(self, queryset=None):    #here slug is used to identify theS particular resturants
        slug = self.kwargs.get("slug")
        obj = get_object_or_404(ResturantLocation, slug=slug)
        return obj

def resturant_createview(request):
    form = ResturantLocationModelForm(request.GET or None)
    errors = ""

    print("request.POST: {}".format(request.POST))
    print("request.GET: {}".format(request.GET))
    print("Form is valid: {}".format(form.is_valid()))

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse_lazy("resturants:list"))
    if form.errors:
        errors = form.errors

    template_name = 'resturants/form.html'
    context = {"resturant_form": form, "form_error": errors}
    return render(request, template_name, context)


class ResturantCreateView(LoginRequiredMixin, CreateView):      #LoginRequireMixin
    #login_url = "/login/"
    login_url = reverse_lazy("userauth:login")
    form_class = ResturantLocationModelForm
    template_name = "resturants/form.html"
    #success_url = "/resturants/"
    success_url = reverse_lazy("resturants:list")


    def form_valid(self, form):
        instance = form.save(commit=False)  #commit=False is used to make temporarily save but not hardcoded(permanently save) in database
        instance.owner =self.request.user
        return super().form_valid(form)




class HomeTemplateView(TemplateView):
        template_name = "resturants/resturants_home.html"

FoodSafari/trydjango2/resturants/templates/resturants/form.html
{% extends "base.html" %}
{% block content %}
    {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'resturants/resturant_list.css' %}">
<hr>
<div class="container">
  <div class="row-fluid">
    <div class="span10 offsetHalf">

		<i class="icon-screenshot icon-5x" style="color:#ee1111;"></i>
    </div>
  </div>

  <div class="row-fluid">

      	<div class="span5 offsetHalf block">
          <div class="pull-center">
              <h1><font color="#ffffff"><h1><b><font size="8">Add Resturant's</font></b></h1></font></h1>
                <form method='POST'>

                    {% csrf_token %}
                   {{ form.as_p }}

                    <button type="submit">Save</button>

                    {% if form_error %}
                        {{ form_error }}
                    {% endif %}


                </form>
          </div>
      	</div>

</div><!---/cont---->

{% endblock %}
</div>

FoodSafari/trydjango2/resturants/templates/resturants/resturant_list.html
{% extends "base.html" %}
{% block content %}
    {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'resturants/resturant_list.css' %}">
<hr>
<div class="container">
  <div class="row-fluid">
    <div class="span10 offsetHalf">

		<i class="icon-screenshot icon-5x" style="color:#ee1111;"></i>
    </div>
  </div>

  <div class="row-fluid">

      	<div class="span5 offsetHalf block">
          <div class="pull-center"><br>
              <h1><font color="#ffffff"><center><h1><b><font size="7">Veg Resturant's</font></b></h1></center></font></h1>
            <b>{% for resturant in object_list %}
              {% if resturant.category == 'veg' %}
                <li style="list-style-type:none;">
                    <a href="{% url 'resturants:detail' slug=resturant.slug %}"><font color="#ffffff"><font size="3"><font size="4"><center>{{ resturant.name }}</center></font></font></font></a>
                </li>
              {% endif %}
            {% endfor %}
            </b></div>
      	</div>
<br><br><br><br><br><br>
      	<div class="span5 offsetHalf block">
          <div class="pull-center"><br>
              <h1><font color="#ffffff"><center><h1><b><font size="7">Non-Veg Resturant's</font></b></h1></center></font></h1>
            <b>{% for resturant in object_list %}
              {% if resturant.category == 'non-veg' %}
                <li style="list-style-type:none;">
                    <a href="{% url 'resturants:detail' slug=resturant.slug %}"><font color="#ffffff"><font size="3"><font size="4"><center>{{ resturant.name }}</center></font></font></font></a>
                </li>
              {% endif %}
            {% endfor %}
            </b></div>
      	</div>

</div><!---/cont---->



    </div>

  </div>

</div><!---/cont---->

<br><br><br><br><br>
<div class="container">

  <div class="row">
    <div class="col-sm-6">
      <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="//www.youtube.com/embed/xE7dmuiQbyU"></iframe>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="//www.youtube.com/embed/XSDv_XL7lI8"></iframe>
      </div>
    </div>
  </div>
</div>


<br><br><br>


{% endblock %}

FoodSafari/trydjango2/resturants/templates/resturants/resturantlocation_detail.html
{% extends "base.html" %}

{% block content %}
    {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'resturants/resturant_list.css' %}">

<hr>

<div class="container">
  <div class="row-fluid">
    <div class="span10 offsetHalf">

		<i class="icon-screenshot icon-5x" style="color:#ee1111;"></i>
    </div>
  </div>

  <div class="row-fluid">

      	<div class="span5 offsetHalf block">
          <div class="pull-center"><br><br>
              <h1><font color="#ffffff"><center><h1><b><font size="7">Resturant's</font></b></h1></center></font></h1><br><br><br>
              <b><font size="4"><h1><b>{{ resturantlocation.name }}</b><small> <b>{{ resturantlocation.category }}</b></small></h1>
                <p>{{ resturantlocation.location }}</p><br>
              <p>Menus: <br><i>{{ resturantlocation.menus }}</i></p>
                <p><i>Added to database on:</i> {{ resturantlocation.timestamp|date }} || <i>Updated:</i> {{ resturantlocation.updated|timesince }} ago</p>
              </font></b>
          </div>
      	</div>

</div><!---/cont---->


{% endblock %}

FoodSafari/trydjango2/resturants/templates/resturants/resturants_home.html
{% extends "base.html" %}

{% block content %}
    {% load static %}
     <link rel="stylesheet" type="text/css" href="{% static 'resturants/home_css.css' %}">

<div class="container">
  <br>
  <div class="row-fluid">
    <div class="span10 offsetHalf">

		<i class="icon-screenshot icon-5x" style="color:#ee1111;"></i>
    </div>
  </div>
	<div class="row-fluid"><br>
      <h1 class="pull-center"><strong><font color="#ffffff"><b><font size="8">FOOD SAFARI</font></b></font></strong></h1>
      <p class="lead pull-center"><font color="#ffffff"><h1><i><b>"Expect the best"</b></i></h1></font></p>
	</div>
  <br><br><br>
  <div class="row-fluid">
        <br><br>
      	<div class="span5 offsetHalf block">
          <div class="pull-center">
            <h1><font color="#ffffff"><center><h1><font size="7">About Us</font></h1></center></font></h1>
            <font color="#ffffff"><center><h4>Food Safari is the fastest, easiest and most convenient way to enjoy the best food of your favourite<br>
                restaurants at home, at the office or wherever you want to.</h4><br>

           <h5>We know that your time is valuable and sometimes every minute in the day counts. That’s why we<br>
             deliver! So you can spend more time doing the things you love.<br></h5></center></font>
          </div>
            <br><br><br><br><br><br>

      	</div>

</div><!---/cont---->

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <style>
  /* Make the image fully responsive */
  .carousel-inner img {
      width: 100%;
      height: 100%;
  }
  </style>
</head>
<body>

<div id="demo" class="carousel slide" data-ride="carousel">

  <!-- Indicators -->
  <ul class="carousel-indicators">
    <li data-target="#demo" data-slide-to="0" class="active"></li>
    <li data-target="#demo" data-slide-to="1"></li>
    <li data-target="#demo" data-slide-to="2"></li>
    <li data-target="#demo" data-slide-to="3"></li>
    <li data-target="#demo" data-slide-to="4"></li>
    <li data-target="#demo" data-slide-to="5"></li>
    <li data-target="#demo" data-slide-to="6"></li>
    <li data-target="#demo" data-slide-to="7"></li>

  </ul>

  <!-- The slideshow -->
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="/static/img/bota.png" alt="Bota" width="1100" height="500">
    </div>
    <div class="carousel-item">
      <img src="/static/img/narayan.png" alt="Narayan" width="1100" height="500">
    </div>
    <div class="carousel-item">
      <img src="/static/img/hyderbad.png" alt="Hyderbad" width="1100" height="500">
    </div>
    <div class="carousel-item">
      <img src="/static/img/chicken.png" alt="Chicken" width="1100" height="500">
    </div>
     <div class="carousel-item">
      <img src="/static/img/kfc.png" alt="KFC" width="1100" height="500">
    </div>
     <div class="carousel-item">
      <img src="/static/img/pizza.png" alt="Pizza" width="1100" height="500">
    </div>
     <div class="carousel-item">
      <img src="/static/img/royal.png" alt="Royal" width="1100" height="500">
    </div>
     <div class="carousel-item">
      <img src="/static/img/star.png" alt="Star" width="1100" height="500">
    </div>

  </div>

  <!-- Left and right controls -->
  <a class="carousel-control-prev" href="#demo" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#demo" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>
</div>
<br><br><br>
</body>
</html>



{% endblock %}